name: Test OIDC login
on:
  workflow_dispatch:

jobs:
  test-oidc:
    environment: dev
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login via OIDC
        uses: azure/login@v1
        with:
          client-id: 560461b1-6b93-4d8e-8d60-b84e38df35ef
          tenant-id: f81d921a-9cda-470d-a8bd-f12b7a65091c
      - name: Verify identity
        run: az account show
